# Generated by Django 4.0.2 on 2022-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_phone_alter_customer_reward_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_points', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reward_points',
        ),
    ]
