# Generated by Django 4.0.2 on 2022-02-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rewardpoints_remove_customer_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reward_points',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
