# Generated by Django 4.0.2 on 2022-02-28 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_swipetime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reward_points',
        ),
        migrations.AddField(
            model_name='swipetime',
            name='reward_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='swipetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 10, 48, 16, 196391)),
        ),
    ]
