# Generated by Django 4.0.2 on 2022-03-02 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer_reward_points_alter_swipetime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swipetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 12, 58, 10, 346869)),
        ),
    ]
